onClipEvent(load){
   _root.thisPoint = {x:0,y:0};
   this.localToGlobal(_root.thisPoint);
   if(_root.boxx.boxx2.boxx7.zonee.hitTest(this))
   {
      _root.boxx.boxx2.boxx7.gotoAndPlay(2);
      _root.lvl_act = 2;
   }
   if(_root.boxx.boxx2.en_1.boxx.zonee.hitTest(this))
   {
      _root.boxx.boxx2.en_1.boxx.gotoAndPlay(159);
   }
   if(_root.boxx.boxx2.en_2.boxx.zonee.hitTest(this))
   {
      _root.boxx.boxx2.en_2.boxx.gotoAndPlay(159);
   }
   if(_root.boxx.boxx2.en_3.boxx.zonee.hitTest(this))
   {
      _root.boxx.boxx2.en_3.boxx.gotoAndPlay(159);
   }
   if(_root.boxx.boxx2.en_4.boxx.zonee.hitTest(this))
   {
      _root.boxx.boxx2.en_4.boxx.gotoAndPlay(159);
   }
   if(_root.boxx.boxx2.en_5.boxx.zonee.hitTest(this))
   {
      _root.boxx.boxx2.en_5.boxx.gotoAndPlay(159);
   }
   if(_root.boxx.boxx2.en_6.boxx.zonee.hitTest(this))
   {
      _root.boxx.boxx2.en_6.boxx.gotoAndPlay(159);
   }
   if(_root.boxx.boxx2.en_7.boxx.zonee.hitTest(this))
   {
      _root.boxx.boxx2.en_7.boxx.gotoAndPlay(159);
   }
   if(_root.boxx.boxx2.en_8.boxx.zonee.hitTest(this))
   {
      _root.boxx.boxx2.en_8.boxx.gotoAndPlay(159);
   }
   if(_root.boxx.boxx2.en_9.boxx.zonee.hitTest(this))
   {
      _root.boxx.boxx2.en_9.boxx.gotoAndPlay(159);
   }
   if(_root.boxx.boxx2.sp_1.boxx.boxx.zonee.hitTest(this))
   {
      _root.boxx.boxx2.sp_1.boxx.boxx.gotoAndPlay(2);
      _root.boxx.boxx2.sp_1.gotoAndPlay(136);
   }
   if(_root.boxx.boxx2.sp_2.boxx.boxx.zonee.hitTest(this))
   {
      _root.boxx.boxx2.sp_2.boxx.boxx.gotoAndPlay(2);
      _root.boxx.boxx2.sp_2.gotoAndPlay(136);
   }
   if(_root.boxx.boxx2.sp_3.boxx.boxx.zonee.hitTest(this))
   {
      _root.boxx.boxx2.sp_3.boxx.boxx.gotoAndPlay(2);
      _root.boxx.boxx2.sp_3.gotoAndPlay(136);
   }
   if(_root.boxx.boxx2.sp_4.boxx.boxx.zonee.hitTest(this))
   {
      _root.boxx.boxx2.sp_4.boxx.boxx.gotoAndPlay(2);
      _root.boxx.boxx2.sp_4.gotoAndPlay(136);
   }
   if(_root.boxx.boxx2.baril.zonee.hitTest(this))
   {
      _root.boxx.boxx2.baril.gotoAndPlay(2);
      _root.boxx.boxx2.explo.gotoAndPlay(2);
   }
   if(_root.boxx.boxx2.mn_1.zonee.hitTest(this))
   {
      _root.boxx.boxx2.mn_1.gotoAndPlay(2);
   }
   if(_root.boxx.boxx2.mn_2.zonee.hitTest(this))
   {
      _root.boxx.boxx2.mn_2.gotoAndPlay(2);
   }
   if(_root.boxx.boxx2.mn_3.zonee.hitTest(this))
   {
      _root.boxx.boxx2.mn_3.gotoAndPlay(2);
   }
   if(_root.boxx.boxx2.win_1.zonee.hitTest(this))
   {
      _root.boxx.boxx2.win_1.gotoAndStop(2);
   }
   if(_root.boxx.boxx2.win_2.zonee.hitTest(this))
   {
      _root.boxx.boxx2.win_2.gotoAndStop(2);
   }
   if(_root.boxx.boxx2.win_3.zonee.hitTest(this))
   {
      _root.boxx.boxx2.win_3.gotoAndStop(2);
   }
   if(_root.boxx.boxx2.win_4.zonee.hitTest(this))
   {
      _root.boxx.boxx2.win_4.gotoAndStop(2);
   }
   if(_root.boxx.boxx2.win_5.zonee.hitTest(this))
   {
      _root.boxx.boxx2.win_5.gotoAndStop(2);
   }
   if(_root.boxx.boxx2.win_6.zonee.hitTest(this))
   {
      _root.boxx.boxx2.win_6.gotoAndStop(2);
   }
   if(_root.boxx.boxx2.win_7.zonee.hitTest(this))
   {
      _root.boxx.boxx2.win_7.gotoAndStop(2);
   }
   if(_root.boxx.boxx2.win_8.zonee.hitTest(this))
   {
      _root.boxx.boxx2.win_8.gotoAndStop(2);
   }
   if(_root.boxx.boxx2.win_9.zonee.hitTest(this))
   {
      _root.boxx.boxx2.win_9.gotoAndStop(2);
   }
   if(_root.boxx.boxx2.win_10.zonee.hitTest(this))
   {
      _root.boxx.boxx2.win_10.gotoAndStop(2);
   }
   if(_root.boxx.boxx2.win_11.zonee.hitTest(this))
   {
      _root.boxx.boxx2.win_11.gotoAndStop(2);
   }
   if(_root.boxx.boxx2.win_12.zonee.hitTest(this))
   {
      _root.boxx.boxx2.win_12.gotoAndStop(2);
   }
   if(_root.boxx.boxx2.win_13.zonee.hitTest(this))
   {
      _root.boxx.boxx2.win_13.gotoAndStop(2);
   }
   if(_root.boxx.boxx2.pad_1.zonee.hitTest(this))
   {
      _root.boxx.boxx2.pad_1.gotoAndStop(2);
   }
   if(_root.boxx.boxx2.heli.heli2.zonee.hitTest(this))
   {
      _root.helienergy = _root.helienergy - 10;
   }
   if(_root.boxx.boxx2.limo.boxx.zonee.hitTest(this))
   {
      _root.boxx.boxx2.limo.boxx.gotoAndStop(2);
   }
}
